
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

public class Main extends javax.swing.JFrame {

    
    NaiveBayes nb = new NaiveBayes();
    
    
    
    DecisionTreeClassifier dt = new DecisionTreeClassifier();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        browsetrain = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        ppanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(31, 22, 214, 34);

        browsetrain.setText("Browse Train Dataset");
        browsetrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsetrainActionPerformed(evt);
            }
        });
        jPanel1.add(browsetrain);
        browsetrain.setBounds(285, 22, 135, 34);

        jButton2.setText("Preprocess");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(31, 87, 99, 34);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1c.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 540, 470);

        jTabbedPane1.addTab("Training", jPanel1);

        jLabel3.setText("Period");

        jLabel5.setText("Symptom 1");

        jLabel6.setText("Symptom 2");

        jLabel7.setText("Symptom 3");

        jLabel8.setText("Symptom 4");

        jButton3.setText("Test Dataset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Preprocess Test Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(jTextField4)
                            .addComponent(jTextField6)
                            .addComponent(jTextField7)
                            .addComponent(jTextField8))))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Testing", jPanel2);

        jButton5.setText("Calssifiy");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Naive Bayes", "Decision Tree" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton6.setText("PreprocessedTestData");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(334, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Classification", jPanel3);

        javax.swing.GroupLayout ppanelLayout = new javax.swing.GroupLayout(ppanel);
        ppanel.setLayout(ppanelLayout);
        ppanelLayout.setHorizontalGroup(
            ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        ppanelLayout.setVerticalGroup(
            ppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(ppanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(ppanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Peformance", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browsetrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsetrainActionPerformed
        // TODO add your handling code here:
        
        
        JFileChooser jc = new JFileChooser(".");


        int ret = jc.showOpenDialog(this);

        if(ret == JFileChooser.APPROVE_OPTION)
        {
            File f  = jc.getSelectedFile();

            String fname = f.getAbsolutePath();

            jTextField1.setText(fname);
            
        }
        
    }//GEN-LAST:event_browsetrainActionPerformed

    
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        File fx = new File("preprocessedtrain.txt");
        fx.delete();

        String filename = jTextField1.getText();
     
        File f = new File(filename);
        String file = f.getName();
     //  System.out.println(file);
    
   
        try
        {
              FileInputStream fstream = new FileInputStream(filename);

              DataInputStream in = new DataInputStream(fstream);

              BufferedReader br = new BufferedReader(new InputStreamReader(in));

              String strLine;
              
             
              
             while ((strLine = br.readLine()) != null)   {
                   
                                     
                      String [] parts = strLine.split(",");
                       
                      String  first = null;
                      
                      String  second = null;
                      
                      String third = null;
                      
                      String  fourth = null;
                      
                      String  fifth = null;
                      
                      String  sixth = null;
                      
                       String seventh = null;
                       
                        String  last = null;
                        
                        
                  
                      
                      if(parts[1].equalsIgnoreCase("m"))
                      {
                           first = "1";
                      }
                      else if(parts[1].equalsIgnoreCase("f"))
                      {
                          first = "2";
                      }
                      
                      
                      
                      
                      if(parts[2].equalsIgnoreCase("Jan-feb"))
                      {
                           second = "1";
                      }
                      else if(parts[2].equalsIgnoreCase("Mar-may"))
                      {
                          second = "2";
                      }
                      else if(parts[2].equalsIgnoreCase("May-sept"))
                      {
                          second = "3";
                      }
                      else if(parts[2].equalsIgnoreCase("Otc-dec"))
                      {
                          second = "4";
                      }
                      
                      
                      
                  
                     if(parts[3].equalsIgnoreCase("cold"))
                      {
                          third = "1";
                      }
                      else if(parts[3].equalsIgnoreCase("sorethroat"))
                      {
                          third = "2";
                      }
                      else if(parts[3].equalsIgnoreCase("asthma"))
                      {
                          third = "3";
                      }
                      
                    else  if(parts[3].equalsIgnoreCase("noravirus"))
                      {
                           third = "4";
                      }
                      else if(parts[3].equalsIgnoreCase("jointpain"))
                      {
                          third = "5";
                      }
                      else if(parts[3].equalsIgnoreCase("heartattack"))
                      {
                          third = "6";
                      }
                     
                      else if(parts[3].equalsIgnoreCase("flu"))
                      {
                           third = "7";
                      }
                      else if(parts[3].equalsIgnoreCase("sunburn"))
                      {
                          third = "8";
                      }
                      else if(parts[3].equalsIgnoreCase("heatstroke"))
                      {
                          third = "9";
                      }
                      else if(parts[3].equalsIgnoreCase("foodpoisoning"))
                      {
                          third = "10";
                      }
                      
                     else if(parts[3].equalsIgnoreCase("diarrhoea"))
                      {
                           third = "11";
                      }
                      else if(parts[3].equalsIgnoreCase("cancer"))
                      {
                          third = "12";
                      }
                      else if(parts[3].equalsIgnoreCase("bp"))
                      {
                          third = "13";
                      }
                      else if(parts[3].equalsIgnoreCase("influenza"))
                      {
                          third = "14";
                      }
                      
                     else if(parts[3].equalsIgnoreCase("cholera"))
                      {
                           third = "15";
                      }
                      
                      else if(parts[3].equalsIgnoreCase("typhoid"))
                      {
                           third = "16";
                      }
                     
                      
                      
                      
                      
                      
                      
                      
                      if(parts[4].equalsIgnoreCase("musclePain"))
                      {
                          fourth = "1";
                      }
                      else if(parts[4].equalsIgnoreCase("sneezing"))
                      {
                          fourth = "2";
                      }
                      else if(parts[4].equalsIgnoreCase("itchiness"))
                      {
                          fourth = "3";
                      }
                      
                      else if(parts[4].equalsIgnoreCase("throatIrritation"))
                      {
                           fourth = "4";
                      }
                      else if(parts[4].equalsIgnoreCase("difficultySwallowing"))
                      {
                          fourth = "5";
                      }
                      else if(parts[4].equalsIgnoreCase("painInThroat"))
                      {
                          fourth = "6";
                      }
                     
                      else if(parts[4].equalsIgnoreCase("vomiting"))
                      {
                           fourth = "7";
                      }
                      else if(parts[4].equalsIgnoreCase("whitePatchesOnTonsils"))
                      {
                          fourth = "8";
                      }
                      else if(parts[4].equalsIgnoreCase("cough"))
                      {
                          fourth = "9";
                      }
                      else if(parts[4].equalsIgnoreCase("wheezing"))
                      {
                          fourth = "10";
                      }
                      
                      else if(parts[4].equalsIgnoreCase("chestPressure"))
                      {
                           fourth = "11";
                      }
                      else if(parts[4].equalsIgnoreCase("fastBreathing"))
                      {
                          fourth = "12";
                      }
                      
                      
                      
                      
                      
                       if(parts[5].equalsIgnoreCase("musclePain"))
                      {
                          fifth = "1";
                      }
                      else if(parts[5].equalsIgnoreCase("sneezing"))
                      {
                          fifth = "2";
                      }
                      else if(parts[5].equalsIgnoreCase("itchiness"))
                      {
                          fifth = "3";
                      }
                      
                      else if(parts[5].equalsIgnoreCase("throatIrritation"))
                      {
                           fifth = "4";
                      }
                      else if(parts[5].equalsIgnoreCase("difficultySwallowing"))
                      {
                          fifth = "5";
                      }
                      else if(parts[5].equalsIgnoreCase("painInThroat"))
                      {
                          fifth = "6";
                      }
                     
                      else if(parts[5].equalsIgnoreCase("vomiting"))
                      {
                           fifth = "7";
                      }
                      else if(parts[5].equalsIgnoreCase("whitePatchesOnTonsils"))
                      {
                          fifth = "8";
                      }
                      else if(parts[5].equalsIgnoreCase("cough"))
                      {
                          fifth = "9";
                      }
                      else if(parts[5].equalsIgnoreCase("wheezing"))
                      {
                          fifth = "10";
                      }
                      
                      else if(parts[5].equalsIgnoreCase("chestPressure"))
                      {
                           fifth = "11";
                      }
                      else if(parts[5].equalsIgnoreCase("fastBreathing"))
                      {
                          fifth = "12";
                      }
                      
                       
                       
                       
                       
                       
                       
                        if(parts[6].equalsIgnoreCase("musclePain"))
                      {
                          sixth = "1";
                      }
                      else if(parts[6].equalsIgnoreCase("sneezing"))
                      {
                          sixth = "2";
                      }
                      else if(parts[6].equalsIgnoreCase("itchiness"))
                      {
                          sixth = "3";
                      }
                      
                      else if(parts[6].equalsIgnoreCase("throatIrritation"))
                      {
                           sixth = "4";
                      }
                      else if(parts[6].equalsIgnoreCase("difficultySwallowing"))
                      {
                          sixth = "5";
                      }
                      else if(parts[6].equalsIgnoreCase("painInThroat"))
                      {
                          sixth = "6";
                      }
                     
                      else if(parts[6].equalsIgnoreCase("vomiting"))
                      {
                           sixth = "7";
                      }
                      else if(parts[6].equalsIgnoreCase("whitePatchesOnTonsils"))
                      {
                          sixth = "8";
                      }
                      else if(parts[6].equalsIgnoreCase("cough"))
                      {
                          sixth = "9";
                      }
                      else if(parts[6].equalsIgnoreCase("wheezing"))
                      {
                          sixth = "10";
                      }
                      
                      else if(parts[6].equalsIgnoreCase("chestPressure"))
                      {
                           sixth = "11";
                      }
                      else if(parts[6].equalsIgnoreCase("fastBreathing"))
                      {
                          sixth = "12";
                      }
                      
                        
                        
                        
                        
                        
                         if(parts[7].equalsIgnoreCase("musclePain"))
                      {
                          seventh = "1";
                      }
                      else if(parts[7].equalsIgnoreCase("sneezing"))
                      {
                          seventh = "2";
                      }
                      else if(parts[7].equalsIgnoreCase("itchiness"))
                      {
                          seventh = "3";
                      }
                      
                      else if(parts[7].equalsIgnoreCase("throatIrritation"))
                      {
                           seventh = "4";
                      }
                      else if(parts[7].equalsIgnoreCase("difficultySwallowing"))
                      {
                          seventh = "5";
                      }
                      else if(parts[7].equalsIgnoreCase("painInThroat"))
                      {
                          seventh = "6";
                      }
                     
                      else if(parts[7].equalsIgnoreCase("vomiting"))
                      {
                           seventh = "7";
                      }
                      else if(parts[7].equalsIgnoreCase("whitePatchesOnTonsils"))
                      {
                          seventh = "8";
                      }
                      else if(parts[7].equalsIgnoreCase("cough"))
                      {
                          seventh = "9";
                      }
                      else if(parts[7].equalsIgnoreCase("wheezing"))
                      {
                          seventh = "10";
                      }
                      
                      else if(parts[7].equalsIgnoreCase("chestPressure"))
                      {
                           seventh = "11";
                      }
                      else if(parts[7].equalsIgnoreCase("fastBreathing"))
                      {
                          seventh = "12";
                      }
                      
                      
                         
                         
                      if(parts[8].equalsIgnoreCase("yes"))
                      {
                           last = "1";
                      }
                      else if(parts[8].equalsIgnoreCase("no"))
                      {
                          last = "0";
                      }
                      
                      String newline = second + "," +   fourth + "," + fifth + "," + sixth 
                              + "," + seventh + "," +last ;
                       FileAppender.AppendtoFile("preprocessedtrain.txt", newline);
                       System.out.println(newline);
                       
                      
                          
                                      
                 
                  

              }
             
              JOptionPane.showMessageDialog(this, "Preprocessed Successfully");
              br.close();
              in.close();
              fstream.close();


        }
        catch(Exception e)
        {
           e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String filename = jTextField11.getText();
         
         
       
        File f = new File(filename);
        String file = f.getName();
        System.out.println(file);
    
        String ct = null;
        try
        {
              FileInputStream fstream = new FileInputStream(filename);

              DataInputStream in = new DataInputStream(fstream);

              BufferedReader br = new BufferedReader(new InputStreamReader(in));

              String strLine;
              
             
              
             while ((strLine = br.readLine()) != null)   {
                   
                                     
                        String [] parts = strLine.split(",");
                        ct = parts[0] + "," + parts[1] + "," + parts[2] + "," + parts[3] + "," + parts[4] ;
                   
                      
                   }
             
              br.close();
              in.close();
              fstream.close();


        }
        catch(Exception e)
        {
           e.printStackTrace();
        }
        
        
                      
        System.out.println(ct);               
                         
                         
         
        
        if(jComboBox1.getSelectedIndex() ==0)
        {
              nb.trainClassifierNB();
        
             System.out.println("Training completed Using Naive Bayes!!!!");
        
         
            boolean res1;
      
            try {
                res1 = nb.isDiseaseNB(ct);
                
                System.out.println("Returned result for Naive Bayes:" + res1);
                
               
                
                if(res1 == true)
                {
                    JOptionPane.showMessageDialog(this, "Predicted with Disease");
                    
                    int dis1 = nb.getSeverity(ct);
                    
                    int dis2 = nb.getdislevel(ct);
                    
                    
                     System.out.println(dis1);
                    
                     System.out.println(dis2);
                     
                    if(dis1 == 1 )
                    {
                        if(dis2 ==1)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Cold with frequently in JAN -FEB");  
                    
                        }
                        if(dis2 ==2)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is SoreThroat with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==3)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Asthma with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==4)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is NeuroVirus with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==5)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is JointPain with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==6)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is HeartAttack with freqiuently in JAN -FEB");  
                    
                        }
                         if(dis2 ==7)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Flu with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==8)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Sunburn with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==9)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is heatstroke with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==10)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is food poison with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==11)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is diarhai with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==12)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cancer with freqiuently in JAN -FEB");  
                    
                        }
                         if(dis2 ==13)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is BP with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==14)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is INFluenza with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==15)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cholera with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==16)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Typhoid with freqiuently in JAN -FEB");  
                    
                        }
                       
                    }
                    else if(dis1 ==2)
                    {
                        //JOptionPane.showMessageDialog(this, "Predicted Disease with freqiuently in MAR -MAY");
                         if(dis2 ==1)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Cold with frequently in MAR-MAY");  
                    
                        }
                        if(dis2 ==2)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is SoreThroat with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==3)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Asthma with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==4)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is NeuroVirus with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==5)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is JointPain with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==6)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is HeartAttack with freqiuently in MAR-MAY");  
                    
                        }
                         if(dis2 ==7)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Flu with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==8)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Sunburn with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==9)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is heatstroke with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==10)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is food poison with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==11)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is diarhai with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==12)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cancer with freqiuently in MAR-MAY");  
                    
                        }
                         if(dis2 ==13)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is BP with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==14)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is INFluenza with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==15)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cholera with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==16)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Typhoid with freqiuently in MAR-MAY");  
                    
                        }
                        
                        
                    }
                    else if(dis1 == 3)
                    {
                       //  JOptionPane.showMessageDialog(this, "Predicted Disease with freqiuently in MAY -SEP");
                         if(dis2 ==1)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Cold with frequently in MAY-SEP");  
                    
                        }
                        if(dis2 ==2)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is SoreThroat with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==3)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Asthma with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==4)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is NeuroVirus with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==5)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is JointPain with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==6)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is HeartAttack with freqiuently in MAY-SEP");  
                    
                        }
                         if(dis2 ==7)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Flu with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==8)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Sunburn with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==9)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is heatstroke with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==10)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is food poison with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==11)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is diarhai with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==12)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cancer with freqiuently in MAY-SEP");  
                    
                        }
                         if(dis2 ==13)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is BP with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==14)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is INFluenza with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==15)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cholera with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==16)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Typhoid with freqiuently in MAY-SEP");  
                    
                        }
                    }
                    else if(dis1 == 4)
                    {
                         //JOptionPane.showMessageDialog(this, "Predicted Disease with freqiuently in OCT -DEC");
                          if(dis2 ==1)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Cold with frequently in OCT -DEC");  
                    
                        }
                        if(dis2 ==2)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is SoreThroat with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==3)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Asthma with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==4)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is NeuroVirus with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==5)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is JointPain with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==6)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is HeartAttack with freqiuently in OCT -DEC");  
                    
                        }
                         if(dis2 ==7)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Flu with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==8)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Sunburn with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==9)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is heatstroke with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==10)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is food poison with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==11)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is diarhai with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==12)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cancer with freqiuently in OCT -DEC");  
                    
                        }
                         if(dis2 ==13)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is BP with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==14)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is INFluenza with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==15)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cholera with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==16)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Typhoid with freqiuently in OCT -DEC");  
                    
                        }
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No Disease, Patient is Healthy");
                }
                
            } catch (Exception ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            
           
        
        }
        else if(jComboBox1.getSelectedIndex() == 1)
        {
             dt.trainClassifierDT();
        
             System.out.println("Training completed Using Decision Tree!!!!");
        
      //  String filename = "preprocessedtest.txt";
         
            boolean res1;
      
            try {
                res1 = dt.isDiseaseDT(ct);
                
                System.out.println("Returned result for Decision Tree:" + res1);
                
                 if(res1 == true)
                {
                    JOptionPane.showMessageDialog(this, "Predicted with Disease");
                    
                    int dis1 = dt.getSeverity(ct);
                    
                    int dis2 = dt.getdislevel(ct);
                    
                    
                     System.out.println(dis1);
                    
                     System.out.println(dis2);
                     
                    if(dis1 == 1 )
                    {
                        if(dis2 ==1)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Cold with frequently in JAN -FEB");  
                    
                        }
                        if(dis2 ==2)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is SoreThroat with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==3)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Asthma with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==4)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is NeuroVirus with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==5)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is JointPain with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==6)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is HeartAttack with freqiuently in JAN -FEB");  
                    
                        }
                         if(dis2 ==7)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Flu with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==8)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Sunburn with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==9)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is heatstroke with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==10)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is food poison with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==11)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is diarhai with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==12)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cancer with freqiuently in JAN -FEB");  
                    
                        }
                         if(dis2 ==13)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is BP with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==14)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is INFluenza with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==15)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cholera with freqiuently in JAN -FEB");  
                    
                        }
                        if(dis2 ==16)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Typhoid with freqiuently in JAN -FEB");  
                    
                        }
                       
                    }
                    else if(dis1 ==2)
                    {
                        //JOptionPane.showMessageDialog(this, "Predicted Disease with freqiuently in MAR -MAY");
                         if(dis2 ==1)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Cold with frequently in MAR-MAY");  
                    
                        }
                        if(dis2 ==2)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is SoreThroat with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==3)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Asthma with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==4)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is NeuroVirus with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==5)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is JointPain with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==6)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is HeartAttack with freqiuently in MAR-MAY");  
                    
                        }
                         if(dis2 ==7)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Flu with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==8)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Sunburn with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==9)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is heatstroke with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==10)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is food poison with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==11)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is diarhai with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==12)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cancer with freqiuently in MAR-MAY");  
                    
                        }
                         if(dis2 ==13)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is BP with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==14)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is INFluenza with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==15)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cholera with freqiuently in MAR-MAY");  
                    
                        }
                        if(dis2 ==16)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Typhoid with freqiuently in MAR-MAY");  
                    
                        }
                        
                        
                    }
                    else if(dis1 == 3)
                    {
                       //  JOptionPane.showMessageDialog(this, "Predicted Disease with freqiuently in MAY -SEP");
                         if(dis2 ==1)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Cold with frequently in MAY-SEP");  
                    
                        }
                        if(dis2 ==2)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is SoreThroat with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==3)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Asthma with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==4)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is NeuroVirus with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==5)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is JointPain with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==6)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is HeartAttack with freqiuently in MAY-SEP");  
                    
                        }
                         if(dis2 ==7)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Flu with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==8)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Sunburn with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==9)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is heatstroke with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==10)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is food poison with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==11)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is diarhai with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==12)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cancer with freqiuently in MAY-SEP");  
                    
                        }
                         if(dis2 ==13)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is BP with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==14)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is INFluenza with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==15)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cholera with freqiuently in MAY-SEP");  
                    
                        }
                        if(dis2 ==16)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Typhoid with freqiuently in MAY-SEP");  
                    
                        }
                    }
                    else if(dis1 == 4)
                    {
                         //JOptionPane.showMessageDialog(this, "Predicted Disease with freqiuently in OCT -DEC");
                          if(dis2 ==1)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Cold with frequently in OCT -DEC");  
                    
                        }
                        if(dis2 ==2)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is SoreThroat with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==3)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Asthma with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==4)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is NeuroVirus with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==5)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is JointPain with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==6)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is HeartAttack with freqiuently in OCT -DEC");  
                    
                        }
                         if(dis2 ==7)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Flu with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==8)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Sunburn with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==9)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is heatstroke with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==10)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is food poison with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==11)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is diarhai with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==12)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cancer with freqiuently in OCT -DEC");  
                    
                        }
                         if(dis2 ==13)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is BP with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==14)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is INFluenza with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==15)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is cholera with freqiuently in OCT -DEC");  
                    
                        }
                        if(dis2 ==16)
                        {
                       JOptionPane.showMessageDialog(this, "Predicted Disease is Typhoid with freqiuently in OCT -DEC");  
                    
                        }
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No Disease, Patient is Healthy");
                }
                
                
               
            } catch (Exception ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
      
          
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  
        JFileChooser jc = new JFileChooser(".");


        int ret = jc.showOpenDialog(this);

        if(ret == JFileChooser.APPROVE_OPTION)
        {
            File f  = jc.getSelectedFile();

            String fname = f.getAbsolutePath();

            jTextField11.setText(fname);
            
        }
                
    }//GEN-LAST:event_jButton6ActionPerformed

    
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        File fx = new File("preprocessedtest.txt");
        fx.delete();

        String filename = jTextField10.getText();
        File f = new File(filename);
        String file = f.getName();
        System.out.println(file);

        try
        {
            FileInputStream fstream = new FileInputStream(filename);

            DataInputStream in = new DataInputStream(fstream);

            BufferedReader br = new BufferedReader(new InputStreamReader(in));

            String strLine;

            while ((strLine = br.readLine()) != null)   {

                String [] parts = strLine.split(",");

           

                String  second = null;

              

                String  fourth = null;

                String  fifth = null;

                String  sixth = null;

                String seventh = null;

                // System.out.println(parts[24]);

               

                if(parts[0].equalsIgnoreCase("Jan-feb"))
                {
                    second = "1";
                }
                else if(parts[0].equalsIgnoreCase("Mar-may"))
                {
                    second = "2";
                }
                else if(parts[0].equalsIgnoreCase("May-sept"))
                {
                    second = "3";
                }
                else if(parts[0].equalsIgnoreCase("Otc-dec"))
                {
                    second = "4";
                }

                
                
                
                if(parts[1].equalsIgnoreCase("musclePain"))
                {
                    fourth = "1";
                }
                else if(parts[1].equalsIgnoreCase("sneezing"))
                {
                    fourth = "2";
                }
                else if(parts[1].equalsIgnoreCase("itchiness"))
                {
                    fourth = "3";
                }

                else if(parts[1].equalsIgnoreCase("throatIrritation"))
                {
                    fourth = "4";
                }
                else if(parts[1].equalsIgnoreCase("difficultySwallowing"))
                {
                    fourth = "5";
                }
                else if(parts[1].equalsIgnoreCase("painInThroat"))
                {
                    fourth = "6";
                }

                else if(parts[1].equalsIgnoreCase("vomiting"))
                {
                    fourth = "7";
                }
                else if(parts[1].equalsIgnoreCase("whitePatchesOnTonsils"))
                {
                    fourth = "8";
                }
                else if(parts[1].equalsIgnoreCase("cough"))
                {
                    fourth = "9";
                }
                else if(parts[1].equalsIgnoreCase("wheezing"))
                {
                    fourth = "10";
                }

                else if(parts[1].equalsIgnoreCase("chestPressure"))
                {
                    fourth = "11";
                }
                else if(parts[1].equalsIgnoreCase("fastBreathing"))
                {
                    fourth = "12";
                }

                if(parts[2].equalsIgnoreCase("musclePain"))
                {
                    fifth = "1";
                }
                else if(parts[2].equalsIgnoreCase("sneezing"))
                {
                    fifth = "2";
                }
                else if(parts[2].equalsIgnoreCase("itchiness"))
                {
                    fifth = "3";
                }

                else if(parts[2].equalsIgnoreCase("throatIrritation"))
                {
                    fifth = "4";
                }
                else if(parts[2].equalsIgnoreCase("difficultySwallowing"))
                {
                    fifth = "5";
                }
                else if(parts[2].equalsIgnoreCase("painInThroat"))
                {
                    fifth = "6";
                }

                else if(parts[2].equalsIgnoreCase("vomiting"))
                {
                    fifth = "7";
                }
                else if(parts[2].equalsIgnoreCase("whitePatchesOnTonsils"))
                {
                    fifth = "8";
                }
                else if(parts[2].equalsIgnoreCase("cough"))
                {
                    fifth = "9";
                }
                else if(parts[2].equalsIgnoreCase("wheezing"))
                {
                    fifth = "10";
                }

                else if(parts[2].equalsIgnoreCase("chestPressure"))
                {
                    fifth = "11";
                }
                else if(parts[2].equalsIgnoreCase("fastBreathing"))
                {
                    fifth = "12";
                }

                if(parts[3].equalsIgnoreCase("musclePain"))
                {
                    sixth = "1";
                }
                else if(parts[3].equalsIgnoreCase("sneezing"))
                {
                    sixth = "2";
                }
                else if(parts[3].equalsIgnoreCase("itchiness"))
                {
                    sixth = "3";
                }

                else if(parts[3].equalsIgnoreCase("throatIrritation"))
                {
                    sixth = "4";
                }
                else if(parts[3].equalsIgnoreCase("difficultySwallowing"))
                {
                    sixth = "5";
                }
                else if(parts[3].equalsIgnoreCase("painInThroat"))
                {
                    sixth = "6";
                }

                else if(parts[3].equalsIgnoreCase("vomiting"))
                {
                    sixth = "7";
                }
                else if(parts[3].equalsIgnoreCase("whitePatchesOnTonsils"))
                {
                    sixth = "8";
                }
                else if(parts[3].equalsIgnoreCase("cough"))
                {
                    sixth = "9";
                }
                else if(parts[3].equalsIgnoreCase("wheezing"))
                {
                    sixth = "10";
                }

                else if(parts[3].equalsIgnoreCase("chestPressure"))
                {
                    sixth = "11";
                }
                else if(parts[3].equalsIgnoreCase("fastBreathing"))
                {
                    sixth = "12";
                }

                if(parts[4].equalsIgnoreCase("musclePain"))
                {
                    seventh = "1";
                }
                else if(parts[4].equalsIgnoreCase("sneezing"))
                {
                    seventh = "2";
                }
                else if(parts[4].equalsIgnoreCase("itchiness"))
                {
                    seventh = "3";
                }

                else if(parts[4].equalsIgnoreCase("throatIrritation"))
                {
                    seventh = "4";
                }
                else if(parts[4].equalsIgnoreCase("difficultySwallowing"))
                {
                    seventh = "5";
                }
                else if(parts[4].equalsIgnoreCase("painInThroat"))
                {
                    seventh = "6";
                }

                else if(parts[4].equalsIgnoreCase("vomiting"))
                {
                    seventh = "7";
                }
                else if(parts[4].equalsIgnoreCase("whitePatchesOnTonsils"))
                {
                    seventh = "8";
                }
                else if(parts[4].equalsIgnoreCase("cough"))
                {
                    seventh = "9";
                }
                else if(parts[4].equalsIgnoreCase("wheezing"))
                {
                    seventh = "10";
                }

                else if(parts[4].equalsIgnoreCase("chestPressure"))
                {
                    seventh = "11";
                }
                else if(parts[4].equalsIgnoreCase("fastBreathing"))
                {
                    seventh = "12";
                }

                String newline =  second + ","  + fourth + "," + fifth + "," + sixth
                + "," + seventh ;
                FileAppender.AppendtoFile("preprocessedtest.txt", newline);
                System.out.println(newline);

            }

            JOptionPane.showMessageDialog(this, "Preprocessed Test Data Successfully");
            br.close();
            in.close();
            fstream.close();

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        JFileChooser jc = new JFileChooser(".");

        int ret = jc.showOpenDialog(this);

        if(ret == JFileChooser.APPROVE_OPTION)
        {
            File f  = jc.getSelectedFile();

            String fname = f.getAbsolutePath();

            jTextField10.setText(fname);

        }

        String filename = jTextField10.getText();

        File ff = new File(filename);
        String file = ff.getName();
        System.out.println(file);

        try
        {
            FileInputStream fstream = new FileInputStream(filename);

            DataInputStream in = new DataInputStream(fstream);

            BufferedReader br = new BufferedReader(new InputStreamReader(in));

            String strLine;

            while ((strLine = br.readLine()) != null)   {

                String [] parts = strLine.split(",");
              
                jTextField4.setText(parts[0]);
              
                jTextField6.setText(parts[1]);

                jTextField7.setText(parts[2]);
                jTextField8.setText(parts[3]);
                jTextField9.setText(parts[4]);

            }

            br.close();
            in.close();
            fstream.close();

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browsetrain;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel ppanel;
    // End of variables declaration//GEN-END:variables
}
